services:
  postgres:
    container_name: postgres
    build:
      context: ./postgres
      dockerfile: Dockerfile.postgres
    restart: unless-stopped
    env_file:
      - ./backend/.env
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    ports:
      - "15432:5432"
    healthcheck:
      # test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
        - TZ=Asia/Jerusalem

  web_collectors:
    container_name: web_collectors
    build:
      context: ./backend
      dockerfile: Dockerfile.web_collectors
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/collectors/logs/db:/app/collectors/logs/db
      - ./backend/collectors/logs/web_collectors:/app/collectors/logs/web_collectors
    environment:
        - TZ=Asia/Jerusalem

  api:
    container_name: api
    build:
      context: ./backend
      dockerfile: Dockerfile.api
    working_dir: /app
    restart: unless-stopped
    env_file:
      - ./backend/.env
    volumes:
      - /opt/ui-dist:/opt/ui-dist
      - ./ui:/ui
    expose:
      - "8000"

  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile.nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./nginx/log:/var/log/nginx
    environment:
      - DOMAIN=${DOMAIN}
    depends_on:
      - api
    extra_hosts:
      - "host.docker.internal:host-gateway"

  certbot:
    container_name: certbot
    restart: unless-stopped
    image: certbot/certbot:latest
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./certbot/log:/var/log
    entrypoint: >
      /bin/sh -c 'trap exit TERM; while :; do sleep 6h & wait $${!}; certbot renew; done'
  
