[project]
name = "collectors"
version = "0.1.0"
description = "Collectors that provides the spot information from clusters"
dependencies = []

[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"
