[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "holycluster"
version = "0.1.0"
dependencies = [
    "httpx==0.23.2",
    "loguru==0.7.2",
    "sqlalchemy==2.0.31",
    "environs==11.0.0",
    "asyncio==3.4.3",
    "asyncpg>=0.29.0",
    "sqlmodel",
    "greenlet>=3.0.0",
    "redis>=6.4.0",
]
